## YAML Template.
KDB\ParametersBundle\Entity\Parameter:
  type: mappedSuperclass
  
  fields:
    name:
      type: string
      length: 255
      unique: true
      
    value:
      type: string
      length: 50
    
    active:
      type: boolean
    
    activates_at:
      type: datetime
      nullable: true
    
    expires_at:
      type: datetime
      nullable: true