## YAML Template.
KDB\ParametersBundle\Entity\Parameter:
  type: mappedSuperclass
  
  fields:
    name:
      type: string
      length: 255
      unique: true
      
    value:
      type: string
      length: 50