parameters:
  kdb_parameters.manager_class: KDB\ParametersBundle\Entity\ParameterManager

services:
  kdb_parameters.manager:
      class: %kdb_parameters.manager_class%
      arguments: ["@doctrine.orm.entity_manager", %kdb_parameters.class%]
