parameters:
  kdb_parameters.manipulator.class: KDB\ParametersBundle\Util\ParametersManipulator
  kdb_parameters.activate: no

services:
    kdb_parameters:
        class: %kdb_parameters.manipulator.class%
        argument: [%kdb_parameters.activate%]
