parameters:
  kdb_parameters.manipulator.class: KDB\ParametersBundle\Util\ParametersManipulator
  kdb_parameters.activate: kdb_default

services:
    kdb_parameters:
        class: %kdb_parameters.manipulator.class%
        arguments: [%kdb_parameters.class%]
    
    kparams:
      alias: kdb_parameters
