parameters:
  kdb_parameters.activate: kdb_default
  kdb_parameters.form.theme: "KDBParametersBundle::form.html.twig"

services:
    kdb_parameters:
        class: %kdb_parameters.manipulator_class%
        arguments: [@kdb_parameters.manager, @service_container]
    
    kparams:
      alias: kdb_parameters
      
    kdb_parameters.entity_manager:
      factory_service: doctrine
      factory_method: getEntityManager
      class: Doctrine\ORM\EntityManager
      
    kdb_parameters.form:
      factory_service: form.factory
      factory_method: createNamed
      class: Symfony\Component\Form\Form
      arguments: [@kdb_parameters.form.xtype, %kdb_parameters.form_name%]
    
    kdb_parameters.form.xtype:
      class: KDB\ParametersBundle\Form\ParameterFormType
      arguments: [%kdb_parameters.class%]
    
    kdb_parameters.form.handler:
      class: KDB\ParametersBundle\Form\ParameterFormHandler
      scope: request
      arguments: [@kdb_parameters.form, @request, @kdb_parameters.manager]
      
    kdb_parameters.twig.extension:
      class: KDB\ParametersBundle\Twig\Extension\KDBParameterExtension
      arguments: [@kparams]
      tags:
        - { name: twig.extension }
    
    kdb_parameters.session.manipulator:
      class: %kdb_parameters.session_manipulator%
      arguments: [@session]
      scope: request
    
    kdb_session:
      alias: kdb_parameters.session.manipulator
      
      
