kdb_parameters_index:
    pattern:  /
    defaults: { _controller: KDBParametersBundle:Default:index }

kdb_parameters_new:
  pattern: /new
  defaults: { _controller: KDBParametersBundle:Default:new }
